version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk8
    commands:
      - echo install
  pre_build:
    commands:
      - echo  pre_build
  build:
    commands:
      - mvn package
      - echo  pre_build
    post_build:
    commands:
      - echo  post_build

artifacts:
  files:
    - target/spring-boot-h2-0.0.1-SNAPSHOT.jar